"""
Django settings for crawler_service project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from celery.schedules import crontab
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b4dumt#td9v)&og)768peofe#05buvuis6#=%bnh4xd@o9!e=@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Celery Beat
    'django_celery_beat',

    # Development apps
    "crawler",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crawler_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crawler_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'postgres'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.environ.get('POSTGRES_HOST', '0.0.0.0'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (Uploaded files)
MEDIA_URL = '/home/hust/data/'
MEDIA_ROOT = '/home/hust/data'
PAPER_PDF_DIR = 'papers'  # This will be used as upload_to path for FileField, relative to MEDIA_ROOT

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Celery Configuration Options (override via env in Docker Compose)
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Celery Beat Settings
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler' # Requires django-celery-beat

# LLM settings (OpenAI-compatible — defaults point at the internal vLLM server)
OPENAI_BASE_URL = os.environ.get('OPENAI_BASE_URL', 'http://117.16.0.116:8084/v1')
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', 'EMPTY')
OPENAI_MODEL = os.environ.get('OPENAI_MODEL', '')

# ArXiv API settings
# arXiv yêu cầu một User-Agent định danh được + tối đa ~1 request / 3 giây.
# Thiếu User-Agent là nguyên nhân chính gây lỗi 429. Nên đặt email liên hệ thật.
ARXIV_API_URL = os.environ.get('ARXIV_API_URL', 'https://export.arxiv.org/api/query')
ARXIV_USER_AGENT = os.environ.get(
    'ARXIV_USER_AGENT',
    'HUST-AI-Assistant-Crawler/1.0 (+https://hust.edu.vn; mailto:admin@hust.edu.vn)',
)
# Số kết quả lấy về trong MỘT request (kích thước trang khi phân trang).
ARXIV_MAX_RESULTS = int(os.environ.get('ARXIV_MAX_RESULTS', '200'))
# Khoảng cách tối thiểu giữa 2 request tới arXiv (giây).
ARXIV_MIN_INTERVAL = float(os.environ.get('ARXIV_MIN_INTERVAL', '3'))
# Cửa sổ ngày để cào (lùi về quá khứ để metadata đã đầy đủ/ổn định trên arXiv).
# Cào các bài submit trong khoảng [today - START, today - END].
ARXIV_LOOKBACK_START_DAYS = int(os.environ.get('ARXIV_LOOKBACK_START_DAYS', '5'))  # mốc xa nhất
ARXIV_LOOKBACK_END_DAYS = int(os.environ.get('ARXIV_LOOKBACK_END_DAYS', '3'))      # mốc gần nhất

# Celery Beat Settings
CELERY_BEAT_SCHEDULE = {
    # [PWC DISABLED] Shared DB has no `crawl_tasks` table (CrawlTask); PWC not implemented yet.
    # 'check-pwc-sitemap': {
    #     'task': 'crawler.tasks.check_pwc_sitemap',
    #     'schedule': crontab(hour=1, minute=0),
    # },
    'crawl-arxiv-daily': {
        'task': 'crawler.tasks.crawl_arxiv_new_papers',
        'schedule': crontab(hour=2, minute=0),
    },
}