# Generated by Django 5.2 on 2025-04-30 09:05

import django.db.models.deletion
import django.utils.timezone
import pathlib
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('doi', models.CharField(blank=True, max_length=200, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('journal_or_conference', models.CharField(max_length=200)),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('doc', 'DOC'), ('txt', 'TXT'), ('html', 'HTML')], default='pdf', max_length=20)),
                ('pdf_file', models.FileField(upload_to=pathlib.PurePosixPath('/home/trungpt/workspace/crawler_service/papers'))),
                ('keywords', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('pdf_url', models.URLField()),
                ('github_url', models.URLField(blank=True, null=True)),
                ('crawled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('download_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('citations_count', models.IntegerField(default=0)),
                ('references', models.ManyToManyField(related_name='referenced_papers', to='crawler.paper')),
            ],
            options={
                'db_table': 'papers',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the dataset (e.g., ImageNet, COCO, SQuAD)', max_length=300, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the dataset.')),
                ('url', models.URLField(blank=True, help_text='Homepage or download URL for the dataset.', max_length=500, null=True)),
                ('modalities', models.CharField(blank=True, help_text='Data modalities (e.g., Image, Text, Audio, Video). Comma-separated if multiple.', max_length=300)),
                ('languages', models.CharField(blank=True, help_text='Languages present in the dataset (e.g., English, Chinese). Comma-separated.', max_length=300)),
                ('licenses', models.CharField(blank=True, help_text='License(s) under which the dataset is available (e.g., CC BY-SA 4.0, MIT). Comma-separated.', max_length=500)),
                ('tasks', models.CharField(blank=True, help_text='Common tasks the dataset is used for (e.g., Image Classification, Question Answering). Comma-separated.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('papers', models.ManyToManyField(blank=True, help_text='Papers that use or reference this dataset.', related_name='datasets', to='crawler.paper')),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
                'db_table': 'datasets',
            },
        ),
        migrations.CreateModel(
            name='CrawlTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('crawling', 'Crawling'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crawl_task', to='crawler.paper')),
            ],
            options={
                'db_table': 'crawl_tasks',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('papers', models.ManyToManyField(related_name='categories', to='crawler.paper')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('affiliation', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('google_scholar_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('papers', models.ManyToManyField(related_name='authors', to='crawler.paper')),
            ],
            options={
                'db_table': 'authors',
            },
        ),
    ]
