# Generated by Django 5.2 on 2025-05-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_category_dataset_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawltask',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
